// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEMl44BuI00oSeMg-IcSMBdCzOJKWUg4Y',
    appId: '1:159254987638:web:84614c1137de7ec9267057',
    messagingSenderId: '159254987638',
    projectId: 'agendacyyf',
    authDomain: 'agendacyyf.firebaseapp.com',
    storageBucket: 'agendacyyf.firebasestorage.app',
    measurementId: 'G-VGCXF5QJMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBq7jAwJumJUQfkkAoK5blEBhpSB8TAg',
    appId: '1:159254987638:android:8bfcd7633976cf91267057',
    messagingSenderId: '159254987638',
    projectId: 'agendacyyf',
    storageBucket: 'agendacyyf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGzg2_ABbA2_ax6HFTDLJ5Hcx6I89v10g',
    appId: '1:159254987638:ios:767ade63d86660e5267057',
    messagingSenderId: '159254987638',
    projectId: 'agendacyyf',
    storageBucket: 'agendacyyf.firebasestorage.app',
    iosBundleId: 'com.example.proyAgenda',
  );
}
